### ISSUE TITLE
Changing the name of a group should update all linked cards

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/RB-workbench#70]
Estimated time: 1 hour

**Comment by ehennestad** [comment]
If the name of i.e TissueSampleCollection is changed, the value should also be updated in TissueSamples that are "PartOf the TissueSampleCollection

**Comment by ehennestad** [comment]
Undo/redo functionality does not work with this fix, i.e traversing the history will not update the linked values in dependent columns.

Should undo/redo be expanded to save all the tables for each element in history? Or is it better to only track changes, and then reverse them on undo/redo?

**Comment by PolarBean** [comment]
I think it should undo all effects of an action, including linking to other values

**Comment by ehennestad** [comment]
https://github.com/Neural-Systems-at-UIO/RB-workbench/pull/89 fixes this
