### ISSUE TITLE
How to resolve instances for Subject/Strain

### ISSUE THREAD

**Issue by ehennestad** [Neural-Systems-at-UIO/RB-workbench#74]
This is a weird case, @archgogo, maybe you can help?

**Comment by archgogo** [comment]
I could extract the list with this:
from fairgraph.openminds.core.research.strain import Strain
AllStrain=Strain.list(fg_client, size=200, from_index=0, api='auto', scope='released', resolved=False, space=None)

**Comment by ehennestad** [comment]
b994270653553a3cd17ae88919c4d1bf8110d95d
