### ISSUE TITLE
Issue with bucket creation in some cases

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/RB-workbench#93]
Bucket fails to load in the file creator app for second project. Not sure if this was a one-time issue or a bug in the workbench. The bucket loads within 30 sec for first project, fails to load for the second project.

**Comment by sharoncy** [comment]
In some cases a bucket is not created when "launch project" is selected. This should raise an error message, something like: "bucket failed to create, delete and try again".

**Comment by PolarBean** [comment]
Is this still an issue?

**Comment by sharoncy** [comment]
I haven't replicated this issue recently but I also haven't tested so much. I'll reopen if the issue reoccurs. Closed 07.09.23
