### ISSUE TITLE
Possible issue with file upload / brain creator

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/RB-workbench#94]
- I tried to upload a series of 23 images. It uploaded 6 images and then stopped with no further info given (they never uploaded). 
- The time of upload was incorrect (I think by 2 hrs, said 12:08 when it was around14:08). 
- There also seemed to be some issue with file selection. I tried to select an image but wasn't able to select any of them. I clicked around and realised I could select the folder but not the individual files. So I created a "brain" based on the folder. Once it started processing, file selection became active, but by this point brain creator was already running. A bug here?
-  "Creating your brain" is "running" but nothing has visibly changed in 5 mins (still says 0%). Not sure if there is something wrong or if it just takes a lot of time. 
- bucket: ewb-6b6710db

**Comment by PolarBean** [comment]
theres an error with creating brains in folders at the moment. Please upload images directly into the bucket (not in folders) until this is fixed :)

**Comment by sharoncy** [comment]
It would be good to be able to delete a "create brain" job. The job I created from the folder is still running. I deleted all the images and tried reuploading 23 images. It loaded the same 6 images as in the first attempt. Is there a max no or max size for upload?

**Comment by PolarBean** [comment]
no but if it crashes on the same image there's a chance something might be up with that image. We will have to investigate.

**Comment by sharoncy** [comment]
I'll shut this issue for now and create new issues as needed after further testing
