### ISSUE TITLE
WebWarp EBRAINS login doesn't work in Firefox. 

### ISSUE THREAD

**Issue by sharoncy** [Neural-Systems-at-UIO/RB-workbench#99]
Login to EBRAINS required on selecting WebWarp. In Firefox, the login does not work. A workaround is to right click > this frame > open frame in new tab. 

![image](https://github.com/Neural-Systems-at-UIO/RB-workbench/assets/30626642/ddc88b32-7c33-46de-939f-2f361cda0ae4)

**Comment by Tevemadar** [comment]
While I do see other problems, the login itself appears to be working.

**Comment by PolarBean** [comment]
just did some testing and it seems like an issue with the sandbox parameter, ill look into this more tomorrow

**Comment by PolarBean** [comment]
fixed
